pipeline 
{
    agent any
    stages
    {
        stage("Calculadora")
        {
            steps
            {
                script
                {
                    def a = 30
                    def b = 2
                    def suma = a + b
                    def resta = a - b
                    def division = a / b
                    def multiplicacion = a * b
                    
                    println "valor 1 = " + a + "\n" + "valor 2 = " + b
                    println "suma = " + suma
                    println "resta = " + resta
                    println "multiplicacion = " + multiplicacion
                    println "division = " + division
                    println " Hola desde la carpeta de Jenkins"
                }
            }
        }
    }
}
